### ISSUE TITLE
Subcommands still working when disabled 

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless-Plugin#62]

**Comment by Lmmb74** [comment]
https://github.com/NamelessMC/Nameless-Plugin/blob/10091c8c4976b1461c97e041bfedb0633a63ba10/NamelessSpigot/src/com/namelessmc/plugin/NamelessSpigot/NamelessPlugin.java#L161
It should be "subcommands-enabled" for subcommands and "individual-commands-enabled" for individuals. Or you should change the the commands.yml to sth looking like this:
 ```yaml
subcommands:
    enabled: true
individuals:
    enabled: true
```
